Feat/testnet
deltaDAO/portal-fmdm pull request #33
Opened 2024-06-25 10:40 UTC by moritzkirstein

2024-07-02 15:04 UTC, Abrom8 requested changes

2024-07-02 15:04 UTC, Abrom8 commented on src/components/ssi/AuthenticationModal/AuthenticationModal.tsx
> +      //   <Modal
question: Is there a reason to keep this code commented?

2024-08-20 14:40 UTC, moritzkirstein commented on src/@utils/compute.ts
> +    for (let i = 0; i < uniqueProviders.length; i++) {
see above

2024-08-20 14:54 UTC, moritzkirstein commented on src/@utils/compute.ts
> +    const inputAsset = assets.find((asset) => asset.id === inputDID[0])
naming is given by the respective type, which in turn is defined by core ocean components like provider (based on its compute response)

my guess is this was changed at some point to be an array without renaming, but we should keep the name common in the stack and avoid translating only on portal level

2024-08-20 14:54 UTC, merged